# Change these first
owner: phantomic12 # Your GitHub organization or username, where this repository lives
repo: uptime-monitor # The name of this repository

sites:
  - name: ptero panel
    url: https://panel.phantomic.live
  - name: replit index
    url: https://onemanager-php.phantomic12.repl.co/
  - name: vercel index
    url: https://onemanager-1-six.vercel.app/
  - name: proxy index
    url: https://index.phantomic.live/
  - name: ptero panel portainer
    url: https://portainer.phantomic.live/
  - name: digitalocean node portainer
    url: https://portainer2.phantomic.live/
  - name: oracle cloud node portainer
    url: https://portainer3.phantomic.live/
  - name: code-server
    url: https://code-server-phantomic12.cloud.okteto.net/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: uptime.phantomic.live
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
